import './globals.css'
import Providers from './layoutProviders/providers'
import ThemeSwitcher from '@/components/ThemeSwitcher'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-skin-base-light dark:bg-skin-base-dark'>
        <Providers>
          <ThemeSwitcher />
          {children}
        </Providers>
      </body>
    </html>
  )
}
